
# OPEN LIBRARIES

```{r}
library(kronos)

#Change sinusoid function to omit NA in the plot
gg_kronos_sinusoid_noNA <- function(kronosOut, fill = "unique_group"){
  
  requireNamespace("ggplot2")
  
  d <- merge(kronosOut@input, kronosOut@to_plot, by="row.names", all=TRUE)[,-1]
  d_noNA <- na.omit(d)
  x_obs  <- paste0(kronosOut@plot_info$time, ".x")
  x_pred = paste0(kronosOut@plot_info$time, ".y")
  y_obs  = colnames(kronosOut@fit$model)[1]
  y_pred = "y_hat"
  fill_obs  = "unique_group.x"
  fill_pred = "unique_group.y"
  period    = kronosOut@plot_info$period
  
  if(sum(grepl(pattern = "unique_group.x|unique_group.y", x = colnames(d))) == 0){
    d$unique_group.x <- ""
    d$unique_group.y <- ""
  }
  ggplot(d) +
    
    geom_rect(data=NULL, aes(xmin=12, xmax=Inf, ymin=-Inf, ymax=Inf), fill="lightgray") +
    
    geom_line(aes_string(x = x_pred, y = y_pred, colour = fill_pred)) +
    
    stat_summary(fun.data = mean_se, geom = "errorbar", position = position_dodge(0.75), width = 1, 
                 aes_string(x = x_obs, y = y_obs, group = fill_obs)) + 
    
    stat_summary(fun = mean, geom="point", position = position_dodge(0.75), size = 4, shape = 21, 
                 aes_string(x = x_obs, y = y_obs, fill = fill_obs)) +
    
    geom_point(data = d_noNA,aes_string(x = x_obs, y = y_obs, fill = fill_obs), shape = 21, position = position_dodge(0.75)) +
    
    scale_x_continuous(breaks = seq(0, period, period/4), expand = c(0, 0)) +
    
    theme_bw() +
    guides(fill = guide_legend("Legend", override.aes = list(size = 3)), colour = guide_none()) +
    
    xlab("") +
    
    ylab("")

}

#Open the rest of the libraries
library(tidyverse)
library(ggplot2)
setwd("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC")

```

# DATA

```{r}
setwd("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC")

library(readxl)
PD35_HPC_bmal1 <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_bmal1.xlsx")
PD35_HPC_bmal1 <- na.omit(PD35_HPC_bmal1)
PD35_HPC_bmal1$Cycle <- factor(PD35_HPC_bmal1$Cycle) #Put "Cycle" as factor

PD35_HPC_clock <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_clock.xlsx")
PD35_HPC_clock <- na.omit(PD35_HPC_clock)
PD35_HPC_clock$Cycle <- factor(PD35_HPC_clock$Cycle) #Put "Cycle" as factor

PD35_HPC_cry1 <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_cry1.xlsx")
PD35_HPC_cry1 <- na.omit(PD35_HPC_cry1)
PD35_HPC_cry1$Cycle <- factor(PD35_HPC_cry1$Cycle) #Put "Cycle" as factor

PD35_HPC_cry2 <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_cry2.xlsx")
PD35_HPC_cry2 <- na.omit(PD35_HPC_cry2)
PD35_HPC_cry2$Cycle <- factor(PD35_HPC_cry2$Cycle) #Put "Cycle" as factor

PD35_HPC_dbp <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_dbp.xlsx")
PD35_HPC_dbp <- na.omit(PD35_HPC_dbp)
PD35_HPC_dbp$Cycle <- factor(PD35_HPC_dbp$Cycle) #Put "Cycle" as factor

PD35_HPC_gsk3b <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_gsk3b.xlsx")
PD35_HPC_gsk3b <- na.omit(PD35_HPC_gsk3b)
PD35_HPC_gsk3b$Cycle <- factor(PD35_HPC_gsk3b$Cycle) #Put "Cycle" as factor

PD35_HPC_nr1d2 <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_nr1d2.xlsx")
PD35_HPC_nr1d2 <- na.omit(PD35_HPC_nr1d2)
PD35_HPC_nr1d2$Cycle <- factor(PD35_HPC_nr1d2$Cycle) #Put "Cycle" as factor

PD35_HPC_per1 <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_per1.xlsx")
PD35_HPC_per1 <- na.omit(PD35_HPC_per1)
PD35_HPC_per1$Cycle <- factor(PD35_HPC_per1$Cycle) #Put "Cycle" as factor

PD35_HPC_per2 <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_per2.xlsx")
PD35_HPC_per2 <- na.omit(PD35_HPC_per2)
PD35_HPC_per2$Cycle <- factor(PD35_HPC_per2$Cycle) #Put "Cycle" as factor

PD35_HPC_rora <- read_excel("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC/PD35_HPC_rora.xlsx")
PD35_HPC_rora <- na.omit(PD35_HPC_rora)
PD35_HPC_rora$Cycle <- factor(PD35_HPC_rora$Cycle) #Put "Cycle" as factor

datasheet_list <- list(PD35_HPC_bmal1, PD35_HPC_clock, PD35_HPC_cry1, PD35_HPC_cry2, PD35_HPC_dbp, PD35_HPC_gsk3b, PD35_HPC_nr1d2, PD35_HPC_per1, PD35_HPC_per2, PD35_HPC_rora)  # Add all your datasheets to this list

levels(PD35_HPC_rora$Cycle) #Posar un dels excels per veure si s'han posat com a factor

```
# CIRCADIAN ANALYSIS

```{r}
library(openxlsx)
setwd("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC")

# List of datasheets (definit previament)
datasheet_list <- list(PD35_HPC_bmal1, PD35_HPC_clock, PD35_HPC_cry1, PD35_HPC_cry2, PD35_HPC_dbp, PD35_HPC_gsk3b, PD35_HPC_nr1d2, PD35_HPC_per1, PD35_HPC_per2, PD35_HPC_rora)  # Add all your datasheets to this list

output_list <- list()

for (i in seq_along(datasheet_list)) {
  output <- kronos(formula = Variable_1 ~ Cycle + time(Timepoint), 
                   data = datasheet_list[[i]], 
                   period = 24, 
                   verbose = TRUE, 
                   pairwise = TRUE)
  
  output_list[[i]] <- output
  
  getKronos_groupwise(output)
  getKronos_pairwise(output)
  getKronos_pairwise_p(output)
}

perform_analysis <- function(datasheet) {
  output <- kronos(formula = Variable_1 ~ Cycle + time(Timepoint), 
                   data = datasheet, 
                   period = 24, 
                   verbose = TRUE, 
                   pairwise = TRUE)
  
  getKronos_groupwise(output)
  getKronos_pairwise(output)
  getKronos_pairwise_p(output)
}

# Assuming datasheet_list contains all your datasheets
lapply(datasheet_list, perform_analysis)

# Create a new workbook
wb <- createWorkbook()

# Extract gene names from datasheet names
gene_names <- c("bmal1", "clock", "cry1", "cry2", "dbp", "gsk3b", "nr1d2", "per1", "per2", "rora")

# Add each output as a sheet to the workbook
for (gene_name in gene_names) {
  addWorksheet(wb, sheetName = gene_name)
}

# Write data to corresponding sheets in the workbook
for (i in seq_along(output_list)) {
  output <- output_list[[i]]
  gene_name <- gene_names[i]
  output_component <- output@ind_fit
  
  writeData(wb, sheet = gene_name, x = output_component, startRow = 1, startCol = 1)
}

# Save the workbook to a file
saveWorkbook(wb, file = "PD35_HPC_all_clock_genes.xlsx", overwrite = TRUE)


# convert cycle in factor in output_list

for(i in seq(length(output_list))){
  output_list[[i]]@input$Cycle = as.factor(output_list[[i]]@input$Cycle)
}
```

# SINUSOID PLOTS

```{r}

# Set the working directory inicial
setwd("/Users/mariareinacampos/Documents/00_MASTER/TFM/Resultats/Results_PD35_HPC")

# Specify the output folder
output_folder <- "Graphs_PD35_HPC"

# Create the output folder if it doesn't exist
if (!file.exists(output_folder)) {
  dir.create(output_folder)
}

# Loop through each output in output_list and generate a plot using gg_kronos_sinusoid
for (i in seq_along(output_list)) {
  output <- output_list[[i]]
  
  # Create a plot for each outcome
  plot <- gg_kronos_sinusoid_noNA(output) +
    scale_colour_manual(values = c("Water" = "#000000", "Ethanol" = "#F764C6")) + #line color
    scale_fill_manual(values = c("Water" = "#FFFFFF", "Ethanol" = "#F764C6")) + #filling color
    xlab("ZT") +
    ylab("Fold change") +
    ggtitle(paste(gene_names[i], "expression", sep = " "))
  
  # Extract gene name for the current iteration
  gene_name <- gene_names[i]
  
  # Save the plot with a unique file name for each output containing the gene name
  file_name <- paste0(output_folder, "/", gene_name, "_PD35_HPC.png")  # For example: _PD35_hpc_bmal1.png 

  # Save the plot as a PNG file with a specific size
  ggsave(file = file_name, plot = plot, width = 6, height = 4, units = "in")
}

```
