
```{r}
library(kronos)
library(tidyverse)
library(ggplot2)
```

Import dataset
```{r}
library(readxl)
bigdata_yjl_ht_new_othergenes <- read_excel("C:/Users/U177202/PhD/Experiments_thesis/Youth_Jet_Lag_Experiment_2/YJL_Exp2_Microarrays/YJL_Exp2_KRONOS/YJL_Exp2_circadian_clock/YJL_Exp2_circadian_clock_ht_extra/bigdata_yjl_ht_new_othergenes_2.3.xlsx")
bigmeta_yjl_ht_new <- read_excel("C:/Users/U177202/PhD/Experiments_thesis/Youth_Jet_Lag_Experiment_2/YJL_Exp2_Microarrays/YJL_Exp2_KRONOS/YJL_Exp2_circadian_clock/YJL_Exp2_circadian_clock_ht_extra/bigmeta_yjl_ht_new_clockgenes.xlsx")
```

'Omics analysis
```{r}
#n = c(rows, columns)
head(bigdata_yjl_ht_new_othergenes, n = c(40, 53))
head(bigmeta_yjl_ht_new)
```

```{r}
out_list_yjl_ht_new_othergenes = fw_kronos(x = bigdata_yjl_ht_new_othergenes, 
                     formula = ~ Group + time(Timepoint), 
                     metadata = bigmeta_yjl_ht_new, 
                     period = 24,
                     verbose = F,
                     pairwise = T)
```



```{r}
fit_df = kronosListToTable(out_list_yjl_ht_new_othergenes)

write.csv(fit_df, "OMICS_yjl_ht_new_othergenes_2.3.5.csv")
```


```{r}
gg_kronos_acrogram(out_list_yjl_ht_new_othergenes)
  scale_fill_manual(values = c("CONTROL" = "#C70E2D",
                               "YJL" = "#9F9EA3"))
```



```{r}
pairwise_list = vector(mode = "list", length = length(out_list_yjl_ht_new_othergenes)) 
for(m in 1:length(out_list_yjl_ht_new_othergenes)){
  pairwise_list[[m]] <- out_list_yjl_ht_new_othergenes [[m]]@pairwise_models
  names(pairwise_list)[m] <- names(out_list_yjl_ht_new_othergenes)[m]}
bound_list <- lapply(X = pairwise_list, FUN = function(x){do.call(rbind, x)})
pairwise_df <- do.call(rbind, bound_list)
pairwise_csv = pairwise_df %>% 
  rownames_to_column("ID") %>%
  separate(col = ID, into = c("Feature","ID"), sep = "\\.", extra = "merge") %>%
  separate(col = ID, into = c("Comparison","Effect"), sep = "\\.")
```


```{r}
plot_list <- vector(mode = "list", length = length(out_list_yjl_ht_new_othergenes))
for(q in 1:length(out_list_yjl_ht_new_othergenes)){
  
  plot_list[[q]] <- gg_kronos_sinusoid(out_list_yjl_ht_new_othergenes[[q]]) }
  
  pdf("Plots_circadian_yjl_ht_new_othergenes_2.3.4.pdf")
for (i in 1:length(plot_list)) {
  print(plot_list[[i]])
}
invisible(dev.off())
```

```{r}
gg_kronos_acrogram <- function(out_list_yjl_ht_new_othergenes){

  d      <- do.call(rbind, lapply(out_list_yjl_ht_new_othergenes, function(x) x@ind_fit))
  period <- out_list_yjl_ht_new_othergenes[[1]]@plot_info$period
  
  ggplot(d) +
    aes_string(x = "acro", fill = "unique_group") +
    
    geom_histogram(position = "identity", color = 'black', alpha = 3/4, bins = period * 2, boundary = 0) + 
    
    coord_polar() +
    
    scale_x_continuous(breaks = seq(0, period, period/6), limits = c(0, period)) +
    
    scale_fill_manual(values = c("Control" = "blue", "YJL" = "red")) + # Setting custom colors
    
    theme_bw()+
    
    guides(fill = guide_legend("Legend"), colour = guide_none(), linetype = guide_none()) +
    
    theme(
      axis.text = element_text(size = 14, colour = "black"), 
      axis.text.y = element_blank(), 
      axis.ticks = element_blank(), 
      panel.grid.major.y = element_line(colour = "darkgray"), 
      panel.border = element_blank() ) +
    
    xlab("") +
    
    ylab("")
 ggsave("kronos_plot.png", p, width = 6, height = 4, units = "in", dpi = 300)
  
  return(p)
  }

```